version: '2'
services:
  api:
    container_name: go-api-starter
    image: go-api-starter/cmd/api
    build:
      context: go
      dockerfile: Dockerfile
      args:
        package: api
    command: ["/go/bin/api"]
    env_file:
      - .env
    links:
      - postgres:postgres
    ports:
      - "8002:8002"
    networks:
      app_net:
        ipv4_address: 10.1.0.10

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/24
        gateway: 10.1.0.1
